export const BMH = [
  {
    id: 1,
    name: 'Kleine Bruthöhle',
    form: 'Höhlen',
    gruppe: 'Spechthöhlen',
    description: 'Durchmesser < 4cm',
    img: 'Kleine_Bruthoehle.png',
  },
  {
    id: 2,
    name: 'Mittelgroße Bruthöhle',
    form: 'Höhlen',
    gruppe: 'Spechthöhlen',
    description: 'Durchmesser < 4-7cm',
    img: 'Mittelgrosse_Bruthoehle.png',
  },
  {
    id: 3,
    name: 'Große Bruthöhle',
    form: 'Höhlen',
    gruppe: 'Spechthöhlen',
    description: 'Durchmesser > 10cm',
    img: 'Grosse_Bruthoehle.png',
  },
  {
    id: 4,
    name: 'Höhlenetage',
    form: 'Höhlen',
    gruppe: 'Spechthöhlen',
    description: '>= 3 auf einer Linie und Durchmesser > 3cm',
    img: 'Hoehlenetage.png',
  },
  {
    id: 5,
    name: 'Mulmhöhle mit Bodenkontakt',
    form: 'Höhlen',
    gruppe: 'Mulmhöhlen',
    description: 'Durchmesser > 10cm',
    img: 'Mulmhoehle_Bodenkontakt.png',
  },
  {
    id: 6,
    name: 'Mulmhöhle ohne Bodenkontakt',
    form: 'Höhlen',
    gruppe: 'Mulmhöhlen',
    description: 'Durchmesser > 10cm',
    img: 'Mulmhoehle_Ohne_Bodenkontakt.png',
  },
  {
    id: 7,
    name: 'Halboffene Mulmhöhle',
    form: 'Höhlen',
    gruppe: 'Mulmhöhlen',
    description: 'Durchmesser > 30cm',
    img: 'Mulmhoehle_Halboffen.png',
  },
  {
    id: 8,
    name: 'Kaminartiger, hohler Stamm',
    form: 'Höhlen',
    gruppe: 'Mulmhöhlen',
    description: 'Durchmesser > 30cm',
    img: 'Hohler_Stamm.png',
  },
  {
    id: 9,
    name: 'Asthöhle',
    form: 'Höhlen',
    gruppe: 'Mulmhöhlen',
    description: 'Durchmesser > 10cm',
    img: 'Asthoehle.png',
  },
  {
    id: 10,
    name: 'Insektengänge und Bohrlöcher',
    form: 'Höhlen',
    gruppe: 'Insektengänge und Bohrlöcher',
    description: 'Durchmesser > 2cm oder Fläche > 300cm^2',
    img: 'Insektengaenge.png',
  },
  {
    id: 11,
    name: 'Dendrotelm oder wassergefüllte Baumhöhlung',
    form: 'Höhlen',
    gruppe: 'Vertiefungen',
    description: 'Durchmesser > 15cm',
    img: 'Dendrotelm_Baumhoehlung.png',
  },
  {
    id: 12,
    name: 'Frasslöcher',
    form: 'Höhlen',
    gruppe: 'Vertiefungen',
    description: 'Durchmesser > 10cm und Höhe > 10cm',
    img: 'Frassloecher.png',
  },
  {
    id: 13,
    name: 'Rindenbedeckte Einbuchtung am Stamm',
    form: 'Höhlen',
    gruppe: 'Vertiefungen',
    description: 'Durchmesser > 10cm und Höhe > 10cm',
    img: 'Rindenbedeckte_Einbuchtung.png',
  },
  {
    id: 14,
    name: 'Stammfußhöhle',
    form: 'Höhlen',
    gruppe: 'Vertiefungen',
    description: 'Durchmesser > 10cm und Dachneigung < 45°',
    img: 'Stammfusshoehle.png',
  },
  {
    id: 15,
    name: 'Holz ohne Rinde',
    form: 'Stammverletzungen und freiliegendes Holz',
    gruppe: 'Freiliegendes Splintholz',
    description: 'Fläche > 300cm^2',
    img: 'Holz_Ohne_Rinde.png',
  },
  {
    id: 16,
    name: 'Brandnarbe',
    form: 'Stammverletzungen und freiliegendes Holz',
    gruppe: 'Freiliegendes Splintholz',
    description: 'Fläche > 600cm^2',
    img: 'Brandnarbe.png',
  },
  {
    id: 17,
    name: 'Rindentasche (unten offen)',
    form: 'Stammverletzungen und freiliegendes Holz',
    gruppe: 'Freiliegendes Splintholz',
    description: 'a > 1cm, b > 10cm, c > 10cm',
    img: 'Rindentasche_Unten_Offen.png',
  },
  {
    id: 18,
    name: 'Rindentasche (oben offen)',
    form: 'Stammverletzungen und freiliegendes Holz',
    gruppe: 'Freiliegendes Splintholz',
    description: 'a > 1cm, b > 10cm, c > 10cm',
    img: 'Rindentasche_Oben_Offen.png',
  },
  {
    id: 19,
    name: 'Stammbruch',
    form: 'Stammverletzungen und freiliegendes Holz',
    gruppe: 'Freiliegendes Splintholz und Kernholz',
    description: 'Durchmesser > 20cm',
    img: 'Stammbruch.png',
  },
  {
    id: 20,
    name: 'Starkastbruch mit freiliegendem Kernholz',
    form: 'Stammverletzungen und freiliegendes Holz',
    gruppe: 'Freiliegendes Splintholz und Kernholz',
    description: 'Fläche > 300cm^2',
    img: 'Starkastbruch.png',
  },
  {
    id: 21,
    name: 'Riss, Spalte',
    form: 'Stammverletzungen und freiliegendes Holz',
    gruppe: 'Freiliegendes Splintholz und Kernholz',
    description: 'Länge > 30cm, Breite > 1cm, Tiefe > 10cm',
    img: 'Riss_Spalte.png',
  },
  {
    id: 22,
    name: 'Blitzrinne',
    form: 'Stammverletzungen und freiliegendes Holz',
    grupp: 'Freiliegendes Splintholz und Kernholz',
    description: 'Länge > 30cm, Breite > 1cm, Tiefe > 10cm',
    img: 'Blitzrinne.png',
  },
  {
    id: 23,
    name: 'Riss bei Zwiesel',
    form: 'Stammverletzungen und freiliegendes Holz',
    grupp: 'Freiliegendes Splintholz und Kernholz',
    description: 'Länge > 30cm',
    img: 'Riss_Zwiesel.png',
  },
  {
    id: 24,
    name: 'Tote Äste',
    form: 'Kronentotholz',
    gruppe: 'Kronentotholz',
    description: 'Durchmesser > 10cm oder Durchmesser > 3cm und 10% Kronentotholz',
    img: 'Tote_Aeste.png',
  },
  {
    id: 25,
    name: 'Abgestorbene Kronenspitzen',
    form: 'Kronentotholz',
    gruppe: 'Kronentotholz',
    description: 'Durchmesser > 10cm an der Basis',
    img: 'Tote_Aeste.png',
  },
  {
    id: 26,
    name: 'Abgebrochener Starkast',
    form: 'Kronentotholz',
    gruppe: 'Kronentotholz',
    description: 'Durchmesser > 20cm, Länge > 50cm',
    img: 'Abgebrochener_Starkast.png',
  },
  {
    id: 27,
    name: 'Hexenbesen',
    form: 'Wucherungen',
    gruppe: 'Hexenbesen und Wasserreiser',
    description: 'Durchmesser > 50cm',
    img: 'Hexenbesen.png',
  },
  {
    id: 28,
    name: 'Wasserreiser',
    form: 'Wucherungen',
    gruppe: 'Hexenbesen und Wasserreiser',
    description: '> 5 Zweige',
    img: 'Wasserreiser.png',
  },
  {
    id: 29,
    name: 'Maserknolle',
    form: 'Wucherungen',
    gruppe: 'Maserknollen und Krebse',
    description: 'Durchmesser > 20cm',
    img: 'Maserknolle.png',
  },
  {
    id: 30,
    name: 'Krebs',
    form: 'Wucherungen',
    gruppe: 'Maserknollen und Krebse',
    description: 'Durchmesser > 20cm oder großer Teil des Stammes bedeckt',
    img: 'Krebs.png',
  },
  {
    id: 31,
    name: 'Mehrjährige Porlinge',
    form: 'Feste und schleimige Pilzfruchtkörper',
    gruppe: 'Mehrjährige Pilzfruchtkörper',
    description: 'Durchmesser > 5cm',
    img: 'Mehrjaehrige_Porlinge.png',
  },
  {
    id: 32,
    name: 'Einjährige Porlinge',
    form: 'Feste und schleimige Pilzfruchtkörper',
    gruppe: 'Kurzlebige Pilzfruchtkörper und Schleimpilze',
    description: 'Durchmesser > 5cm oder > 10',
    img: 'Einjaehrige_Porlinge.png',
  },
  {
    id: 33,
    name: 'Ständerpilze',
    form: 'Feste und schleimige Pilzfruchtkörper',
    gruppe: 'Kurzlebige Pilzfruchtkörper und Schleimpilze',
    description: 'Durchmesser > 5cm oder > 10',
    img: 'Staenderpilze.png',
  },
  {
    id: 34,
    name: 'Große Ascomyceten',
    form: 'Feste und schleimige Pilzfruchtkörper',
    gruppe: 'Kurzlebige Pilzfruchtkörper und Schleimpilze',
    img: 'Grosse_Ascomyceten.png',
  },
  {
    id: 35,
    name: 'Myxomyceten',
    form: 'Feste und schleimige Pilzfruchtkörper',
    gruppe: 'Kurzlebige Pilzfruchtkörper und Schleimpilze',
    img: 'Myxomyceten.png',
  },
  {
    id: 36,
    name: 'Moose oder Lebermoose',
    form: 'Epiphytische, epixylische und parasitische Strukturen',
    gruppe: 'Pflanzen und Flechten, epiphytisch oder prasitisch',
    description: '> 10% des Stammes bedeckt',
    img: 'Moose_Lebermoose.png',
  },
  {
    id: 37,
    name: 'Blatt- oder Strauchflechten',
    form: 'Epiphytische, epixylische und parasitische Strukturen',
    gruppe: 'Pflanzen und Flechten, epiphytisch oder prasitisch',
    description: '> 10% des Stammes bedeckt',
    img: 'Blatt_Strauchflechten.png',
  },
  {
    id: 38,
    name: 'Efeu oder Lianen',
    form: 'Epiphytische, epixylische und parasitische Strukturen',
    gruppe: 'Pflanzen und Flechten, epiphytisch oder prasitisch',
    description: '> 10% des Stammes bedeckt',
    img: 'Efeu_Lianen.png',
  },
  {
    id: 39,
    name: 'Farne',
    form: 'Epiphytische, epixylische und parasitische Strukturen',
    gruppe: 'Pflanzen und Flechten, epiphytisch oder prasitisch',
    description: '> 5 Farnwedel',
    img: 'Farne.png',
  },
  {
    id: 40,
    name: 'Misteln',
    form: 'Epiphytische, epixylische und parasitische Strukturen',
    gruppe: 'Pflanzen und Flechten, epiphytisch oder prasitisch',
    description: '> 20cm',
    img: 'Misteln.png',
  },
  {
    id: 41,
    name: 'Nester von Wirbeltieren',
    form: 'Epiphytische, epixylische und parasitische Strukturen',
    gruppe: 'Nester',
    img: 'Nester_Wirbeltier.png',
  },
  {
    id: 42,
    name: 'Nester von Wirbellosen',
    form: 'Epiphytische, epixylische und parasitische Strukturen',
    gruppe: 'Nester',
    img: 'Nester_Wirbellose.png',
  },
  {
    id: 43,
    name: 'Mikroboden (Rinde)',
    form: 'Epiphytische, epixylische und parasitische Strukturen',
    gruppe: 'Mikroböden',
    img: 'Mikroboden_Rinde.png',
  },
  {
    id: 44,
    name: 'Mikroboden (Krone)',
    form: 'Epiphytische, epixylische und parasitische Strukturen',
    gruppe: 'Mikroböden',
    img: 'Mikroboden_Krone.png',
  },
  {
    id: 45,
    name: 'Aktiver Saftfluss',
    form: 'Ausflüsse',
    gruppe: 'Saft und Harzflüsse',
    img: 'Aktiver_Saftfluss.png',
  },
  {
    id: 46,
    name: 'Aktiver Harzfluss',
    form: 'Ausflüsse',
    gruppe: 'Saft und Harzflüsse',
    img: 'Aktiver_Harzfluss.png',
  },
];
